Repository silverstripe/silverstripe-ckan-registry, pull requests merged in 2018-12, with the labels that each got.

#31 NEW Add CKANRegistryPage with ItemsPerPage setting for frontend pagination size
  lang/_manifest_exclude
  lang/en.yml
  src/CKANRegistryPage.php
  src/Page/CKANRegistryPage.php
  tests/CKANRegistryPageTest.php
  tests/Page/CKANRegistryPageTest.php
  tests/Page/CKANRegistryPageTest.yml
Labels: affects/v4, change/minor

#40 PHPDoc updates, beforeCMSFields implementation, add some tests
  src/Model/Resource.php
  src/Model/ResourceField.php
  src/Model/ResourceFilter.php
  src/Page/CKANRegistryPage.php
  tests/Model/ResourceFieldTest.php
  tests/Model/ResourceFilterTest.php
  tests/Model/ResourceTest.php
  tests/Model/ResourceTest.yml
Labels: affects/v4, change/patch

#44 FIX Remove non-alphanumeric characters from the readable field name
  src/Service/ResourceFieldPopulator.php
  tests/Service/ResourceFieldPopulatorTest.php
Labels: affects/v4, change/patch

#42 FIX Order should auto increment when populating fields
  src/Service/ResourceFieldPopulator.php
  tests/Service/ResourceFieldPopulatorTest.php
Labels: affects/v4, change/patch

#51 Ability to add filters, and configure them
  src/Model/ResourceFilter.php
  src/Model/ResourceFilter/Dropdown.php
  src/Page/CKANRegistryPage.php
  tests/Model/ResourceFilter/DropdownTest.php
  tests/Model/ResourceFilterTest.php
  tests/Model/ResourceFilterTest/InvalidResourceFilter.php
Labels: affects/v4, change/major

#49 NEW Add ResultConditionsField with React component, allows matching column content rules
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/lang/src/en.json
  client/src/boot/registerComponents.js
  client/src/bundles/bundle.js
  client/src/components/CKANResourceLocator.js
  client/src/components/ResultConditions.js
  client/src/components/ResultConditions.scss
  client/src/components/tests/ResultConditions-test.js
  client/src/legacy/CKANResourceLoader-entwine.js
  client/src/legacy/ResultConditions-entwine.js
  client/src/styles/bundle.scss
  package.json
  phpcs.xml.dist
  src/Forms/ResultConditionsField.php
  src/Model/ResourceField.php
  templates/SilverStripe/CKANRegistry/Forms/ResourceLocatorField_holder.ss
  templates/SilverStripe/CKANRegistry/Forms/ResultConditionsField_holder.ss
  tests/Forms/ResultConditionsFieldTest.php
  tests/Model/ResourceFieldTest.php
Labels: affects/v4, change/minor

#56 Add tests for ResourceLocatorField
  tests/Forms/ResourceLocatorFieldTest.php
Labels: affects/v4, change/minor
