Repository silverstripe/silverstripe-ckan-registry, pull requests merged in 2019-02, with the labels that each got.

#173 NEW Adding permalinking for filters, sorting, and page numbers
  client/dist/js/bundle-admin.js
  client/dist/js/bundle.js
  client/src/components/CKANRegistryDisplay.js
  client/src/components/CKANRegistryFilterContainer.js
  client/src/components/tests/CKANRegistryDisplay-test.js
  client/src/lib/CKANApi/DataStore.js
  client/src/lib/CKANApi/DataStore/Query.js
  client/src/lib/CKANApi/DataStore/tests/Query-test.js
  client/src/lib/CKANApi/tests/DataStore-test.js
  package.json
  src/Model/ResourceFilter.php
  yarn.lock
Labels: affects/v4, change/minor

#163 Add user documentation
  README.md
  docs/en/index.md
  docs/en/userguide/_images/change-resource.png
  docs/en/userguide/_images/configure-column.png
  docs/en/userguide/_images/delimiter-use.png
  docs/en/userguide/_images/dropdown-filter-config.png
  docs/en/userguide/_images/in-results-enabled-frontend.png
  docs/en/userguide/_images/in-results-enabled.png
  docs/en/userguide/_images/manual-dropdown-frontend.png
  docs/en/userguide/_images/manual-dropdown.png
  docs/en/userguide/_images/populated-columns.png
  docs/en/userguide/_images/resource-selection.png
  docs/en/userguide/_images/text-filter-config.png
  docs/en/userguide/index.md
Labels: affects/v4, type/docs

#183 FIX Filters now respect their sort order on the frontend
  src/Page/CKANRegistryPageController.php
Labels: affects/v4, change/patch

#185 Add PHP 7.3 to build matrix
  .travis.yml
Labels: affects/v4, change/patch

#188 FIX Readable Label (columns) and Filter Label (filters) are now visible columns on mobile
  client/dist/styles/bundle-admin.css
  client/src/styles/CMSLegacy.scss
  src/Page/CKANRegistryPage.php
  tests/Page/CKANRegistryPageTest.php
Labels: affects/v4, change/patch

#187 FIX Do not display validation error on initial loading
  client/dist/js/bundle-admin.js
  client/src/components/CKANResourceLocatorField.js
Labels: affects/v4, change/patch

#184 NEW Example frontend app client configuration is now exposed via an API endpoint and fetched
  client/dist/js/bundle.js
  client/src/components/CKANExampleApp.js
  client/src/legacy/CKANExampleApp-loader.js
  docs/en/frontend.md
  src/Page/CKANRegistryPageController.php
  templates/Includes/CKANRegistry.ss
  templates/SilverStripe/CKANRegistry/Includes/CKANRegistry.ss
  tests/Page/CKANRegistryPageControllerFunctionalTest.php
Labels: affects/v4, change/minor

#178 FIX Query now accepts field types array and will cast numeric fields as text
  client/dist/js/bundle.js
  client/src/components/CKANRegistryDisplay.js
  client/src/components/tests/CKANRegistryDisplay-test.js
  client/src/lib/CKANApi/DataStore/Query.js
  client/src/lib/CKANApi/DataStore/tests/Query-test.js
  src/Page/CKANRegistryPageController.php
  tests/Page/CKANRegistryPageControllerTest.php
Labels: affects/v4, change/major

#186 FIX Example app displays wider filter column on medium viewports
  client/dist/js/bundle.js
  client/src/components/CKANRegistryDisplay.js
Labels: affects/v4, change/patch

#190 FIX Checkboxes in PresentedOptionsField now have correct Bootstrap classes
  client/dist/js/bundle-admin.js
  client/dist/styles/bundle-admin.css
  client/src/components/CKANPresentedOptionsField.js
  client/src/components/CKANPresentedOptionsField.scss
Labels: affects/v4, change/patch

#191 FIX Slashes in original labels are no longer removed in readable labels
  src/Service/ResourcePopulator.php
  tests/Service/ResourcePopulatorTest.php
Labels: affects/v4, change/patch

#192 FIX Frontend display now uses Bootstrap form control styles for pagination
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/CKANRegistryDisplay.js
  client/src/components/CKANRegistryDisplay.scss
Labels: affects/v4, change/patch

#197 FIX Show "no results" message when no visible fields are available
  client/dist/js/bundle.js
  client/src/components/CKANRegistryDisplay.js
  client/src/components/tests/CKANRegistryDisplay-test.js
Labels: affects/v4, change/patch

#198 NEW Read only support for the React components in this module
  client/dist/js/bundle-admin.js
  client/dist/styles/bundle-admin.css
  client/src/components/CKANPresentedOptionsField.js
  client/src/components/CKANPresentedOptionsField.scss
  client/src/components/CKANResourceLocatorField.js
  client/src/components/CKANResourceLocatorField.scss
  client/src/components/CKANResourceLocatorField/URLInput.js
  client/src/components/CKANResultConditionsField.js
  client/src/components/CKANResultConditionsField.scss
  client/src/components/tests/CKANResourceLocatorField-test.js
  client/src/legacy/CKANResourceLocatorField-entwine.js
  src/Forms/GridFieldResourceTitle.php
  src/Forms/PresentedOptionsField.php
  src/Forms/ResourceLocatorField.php
  src/Forms/ResultConditionsField.php
  src/Page/CKANRegistryPage.php
  templates/SilverStripe/CKANRegistry/Forms/GridFieldResourceTitle.ss
  templates/SilverStripe/CKANRegistry/Forms/ResourceLocatorField_holder.ss
Labels: affects/v4, change/major
