Repository silverstripe/silverstripe-ckan-registry, pull requests merged in 2019-01, with the labels that each got.

#78 API Rename DB fields and update CMS field order and presentation to match designs
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/bundles/bundle.js
  client/src/legacy/ResourceFilter.js
  client/src/styles/CMSLegacy.scss
  src/Model/Resource.php
  src/Model/ResourceField.php
  src/Model/ResourceFilter.php
  src/Page/CKANRegistryPage.php
  src/Service/ResourceFieldPopulator.php
  tests/Model/ResourceFilterTest.php
  tests/Service/ResourceFieldPopulatorTest.php
Labels: affects/v4, change/major

#77 API Rename React form field components to have CKAN prefix and Field suffix
  client/dist/js/bundle.js
  client/src/boot/registerComponents.js
  client/src/bundles/bundle.js
  client/src/components/CKANResourceLocatorField.js
  client/src/components/CKANResourceLocatorField.scss
  client/src/components/CKANResourceLocatorField/URLInput.js
  client/src/components/CKANResultConditionsField.js
  client/src/components/CKANResultConditionsField.scss
  client/src/components/tests/CKANResultConditionsField-test.js
  client/src/legacy/CKANResourceLoaderField-entwine.js
  client/src/legacy/CKANResultConditionsField-entwine.js
  client/src/styles/bundle.scss
Labels: affects/v4, change/major

#88 FIX Remove Add New and Delete GridField actions for data columns on CKAN pages
  src/Page/CKANRegistryPage.php
Labels: affects/v4, change/patch

#90 API Rename ShowInSummaryView, relabel Presented Order, consolidate label lowercasing
  client/lang/src/en.json
  lang/en.yml
  src/Model/ResourceField.php
  src/Model/ResourceFilter.php
  src/Model/ResourceFilter/Dropdown.php
  src/Page/CKANRegistryPage.php
  tests/Model/ResourceFilter/DropdownTest.php
  tests/Model/ResourceFilterTest.php
  tests/Page/CKANRegistryPageTest.php
Labels: affects/v4, change/major

#89 FIX Remove divider line underneath locator field and ensure schema data is passed through
  client/dist/js/bundle.js
  client/src/legacy/CKANResourceLoaderField-entwine.js
  src/Forms/ResourceLocatorField.php
  src/Page/CKANRegistryPage.php
Labels: affects/v4, change/patch

#91 API Refactor CKAN API client and resource population to support metadata retrieval
  README.md
  _config/services.yml
  src/Model/Resource.php
  src/Page/CKANRegistryPage.php
  src/Service/APIClient.php
  src/Service/APIClientInterface.php
  src/Service/ResourceFieldPopulator.php
  src/Service/ResourceFieldPopulatorInterface.php
  src/Service/ResourcePopulator.php
  src/Service/ResourcePopulatorInterface.php
  tests/Forms/ResourceLocatorFieldTest.php
  tests/Model/ResourceTest.php
  tests/Page/CKANRegistryPageTest.php
  tests/Service/APIClientTest.php
  tests/Service/ResourceFieldPopulatorTest.php
  tests/Service/ResourcePopulatorTest.php
Labels: affects/v4, change/major

#93 NEW ShowInDetailView now defaults to true
  src/Model/ResourceField.php
Labels: affects/v4, change/minor

#105 NEW Update default CKAN endpoint to demo.ckan.org
  src/Forms/ResourceLocatorField.php
Labels: affects/v4, change/minor

#104 NEW Filters now have AllColumns checked by default, and have "Search" as a default label
  src/Model/ResourceFilter.php
  tests/Model/ResourceFilterTest.php
Labels: affects/v4, change/minor

#106 FIX Display resource and dataset title in its own component with edit toggle for loader
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/bundles/bundle.js
  client/src/legacy/GridFieldResourceTitle.js
  client/src/styles/GridFieldResourceTitle.scss
  client/src/styles/bundle.scss
  src/Forms/GridFieldResourceTitle.php
  src/Forms/ResourceLocatorField.php
  src/Page/CKANRegistryPage.php
  templates/SilverStripe/CKANRegistry/Forms/GridFieldResourceTitle.ss
  templates/SilverStripe/CKANRegistry/Forms/ResourceLocatorField_holder.ss
  tests/Forms/GridFieldResourceTitleTest.php
  tests/Forms/ResourceLocatorFieldTest.php
Labels: affects/v4, change/patch

#108 API Rename CKANResourceLoaderField-entwine.js to CKANResourceLocatorField-entwine.js
  client/dist/js/bundle.js
  client/src/bundles/bundle.js
  client/src/legacy/CKANResourceLocatorField-entwine.js
Labels: affects/v4, change/major

#110 FIX when no data is set, show the ResourceLocatorField by default
  templates/SilverStripe/CKANRegistry/Forms/ResourceLocatorField_holder.ss
Labels: affects/v4, change/patch, effort/easy, impact/critical, type/bug

#117 FIX Ensure fields and filters are actually deleted rather than just unassociated
  src/Model/Resource.php
  tests/Model/ResourceTest.php
Labels: affects/v4, change/patch

#116 FIX Use the resource ID not the dataset ID, fixes broken initial save
  client/dist/js/bundle.js
  client/lang/src/en.json
  client/src/components/CKANResourceLocatorField.js
  client/src/components/tests/CKANPresentedOptionsField-test.js
  client/src/components/tests/CKANResourceLocatorField-test.js
  client/src/components/tests/CKANResultConditionsField-test.js
  package.json
  yarn.lock
Labels: affects/v4, change/patch

#119 FIX Resolved an issue where an unresolved promise warning was showing in tests
  client/dist/js/bundle.js
  client/src/lib/CKANApi/DataStore.js
  client/src/lib/tests/CKANApi-test.js
Labels: affects/v4, change/patch

#120 FIX Updating GridFieldDetailForm saving of ResourceFields to not create invalid ordering when updating the order field
  src/Forms/GridField/GridFieldDetailForm/ResourceFieldItemRequest.php
  src/Model/ResourceField.php
  src/Page/CKANRegistryPage.php
  tests/Forms/GridField/GridFieldDetailForm/ResourceFieldItemRequest.yml
  tests/Forms/GridField/GridFieldDetailForm/ResourceFieldItemRequestTest.php
Labels: affects/v4, change/patch

#102 NEW Add SiteTree icon for CKANRegistryPage
  src/Page/CKANRegistryPage.php
Labels: affects/v4, change/minor

#125 FIX Add underline to "try again" link in error notice
  client/dist/styles/bundle.css
  client/src/components/CKANPresentedOptionsField.scss
Labels: affects/v4, change/patch

#114 FIX Ensure URLInput does track changes, and fix missing requestAnimationFrame error in tests
  client/dist/js/bundle.js
  client/src/components/CKANResourceLocatorField.js
  package.json
  yarn.lock
Labels: affects/v4, change/patch

#130 FIX Center inline editable checkboxes in columns GridField
  client/dist/styles/bundle.css
  client/src/styles/CMSLegacy.scss
Labels: affects/v4, change/patch

#126 NEW Notify users when changing a dataset or resource that columns/filters will be lost
  client/dist/js/bundle.js
  client/lang/src/en.json
  client/src/components/CKANResourceLocatorField.js
  client/src/components/tests/CKANResourceLocatorField-test.js
Labels: affects/v4, change/minor

#132 FIX Removed trim() null pointer error, and on integers
  client/dist/js/bundle.js
  client/src/components/CKANPresentedOptionsField.js
  client/src/components/tests/CKANPresentedOptionsField-test.js
Labels: affects/v4, change/patch

#122 NEW render table for hosting CKAN resource data
  _config/config.yml
  client/dist/js/bundle-admin.js
  client/dist/js/bundle.js
  client/dist/styles/bundle-admin.css
  client/dist/styles/bundle.css
  client/lang/src/en.json
  client/src/bundles/bundle-admin.js
  client/src/bundles/bundle.js
  client/src/components/CKANRegistryDisplay.js
  client/src/legacy/CKANRegistryDisplay-loader.js
  client/src/styles/bundle-admin.scss
  client/src/styles/bundle.scss
  package.json
  src/Model/Resource.php
  src/Page/CKANRegistryPage.php
  templates/SilverStripe/CKANRegistry/Includes/CKANRegistry.ss
  templates/SilverStripe/CKANRegistry/Page/Layout/CKANRegistryPage.ss
  webpack.config.js
  yarn.lock
Labels: affects/v4, change/minor

#135 NEW TextFilter and DropdownFilter components
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/bundles/bundle.js
  client/src/components/CKANDropdownFilter.js
  client/src/components/CKANTextFilter.js
  client/src/components/tests/CKANDropdownFilter-story.js
  client/src/components/tests/CKANDropdownFilter-test.js
  client/src/components/tests/CKANTextFilter-story.js
  client/src/components/tests/CKANTextFilter-test.js
  client/src/styles/bundle.scss
  package.json
  webpack.config.js
Labels: affects/v4, change/minor

#124 FIX Remove default "Search" filter label
  src/Model/ResourceFilter.php
  tests/Model/ResourceFilterTest.php
Labels: affects/v4, change/patch

#136 API Implement react-router in frontend example app
  client/dist/js/bundle.js
  client/src/bundles/bundle.js
  client/src/components/CKANExampleApp.js
  client/src/components/CKANRegistryDetailView.js
  client/src/components/CKANRegistryDisplay.js
  client/src/components/tests/CKANExampleApp-test.js
  client/src/legacy/CKANExampleApp-loader.js
  client/src/legacy/CKANRegistryDisplay-loader.js
  package.json
  src/Model/Resource.php
  src/Page/CKANRegistryPage.php
  src/Page/CKANRegistryPageController.php
  templates/SilverStripe/CKANRegistry/Includes/CKANRegistry.ss
  templates/SilverStripe/CKANRegistry/Page/Layout/CKANRegistryPage.ss
  tests/Model/ResourceTest.yml
  tests/Page/CKANRegistryPageControllerTest.php
  tests/Page/CKANRegistryPageControllerTest.yml
  yarn.lock
Labels: affects/v4, change/major

#137 NEW Show results on the front-end of a CKAN Registry Page
  client/dist/js/bundle-admin.js
  client/dist/js/bundle.js
  client/src/components/CKANExampleApp.js
  client/src/components/CKANRegistryDisplay.js
  client/src/lib/CKANApi/DataStore.js
  client/src/lib/CKANApi/tests/DataStore-test.js
  src/Page/CKANRegistryPage.php
  src/Page/CKANRegistryPageController.php
  templates/Includes/CKANRegistry.ss
Labels: affects/v4, change/minor

#149 NEW Implementing a clear button for filters on CKAN registry pages
  client/dist/js/bundle.js
  client/src/components/CKANDropdownFilter.js
  client/src/components/CKANRegistryFilterContainer.js
  client/src/components/CKANTextFilter.js
Labels: affects/v4, change/minor

#150 NEW Add detail view for a record when clicked in the table
  client/dist/js/bundle-admin.js
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/lang/src/en.json
  client/src/components/CKANExampleApp.js
  client/src/components/CKANRegistryDetailView.js
  client/src/components/CKANRegistryDetailView.scss
  client/src/components/CKANRegistryDisplay.js
  client/src/components/CKANRegistryDisplay.scss
  client/src/components/tests/CKANExampleApp-test.js
  client/src/components/tests/CKANRegistryDetailView-test.js
  client/src/components/tests/CKANRegistryDisplay-test.js
  client/src/lib/CKANApi/DataStore.js
  client/src/lib/CKANApi/DataStore/Query.js
  client/src/lib/CKANApi/tests/DataStore-test.js
  client/src/styles/bundle.scss
  composer.json
  package.json
  src/Page/CKANRegistryPageController.php
  templates/SilverStripe/CKANRegistry/Includes/CKANRegistry.ss
  templates/SilverStripe/CKANRegistry/Page/Layout/CKANRegistryPage.ss
  yarn.lock
Labels: affects/v4, change/major

#158 DOCS Add developer documentation and overview to the readme
  README.md
  client/src/lib/CKANApi.js
  docs/en/api-clients.md
  docs/en/cms.md
  docs/en/frontend.md
  docs/en/index.md
  docs/en/notes.md
  docs/en/overview.md
Labels: affects/v4, type/docs

#157 NEW Add default filters to data grid and flexibility to Query filter conditions
  client/dist/js/bundle-admin.js
  client/dist/js/bundle.js
  client/src/components/CKANRegistryDetailView.js
  client/src/components/CKANRegistryDisplay.js
  client/src/components/CKANResultConditionsField.js
  client/src/components/tests/CKANRegistryDisplay-test.js
  client/src/components/tests/CKANResultConditionsField-test.js
  client/src/lib/CKANApi/DataStore/Query.js
  client/src/lib/CKANApi/DataStore/tests/Query-test.js
  src/Page/CKANRegistryPageController.php
  tests/Page/CKANRegistryPageControllerTest.php
  tests/Page/CKANRegistryPageControllerTest.yml
Labels: affects/v4, change/minor

#160 NEW Adding the ability to query DISTINCT per column with the Query API
  client/dist/js/bundle.js
  client/src/components/CKANRegistryDisplay.js
  client/src/components/tests/CKANRegistryDisplay-test.js
  client/src/lib/CKANApi/DataStore/Query.js
  client/src/lib/CKANApi/DataStore/tests/Query-test.js
  docs/en/api-clients.md
Labels: affects/v4, change/minor
